name: Build and Deploy React App

on:
  push: 
    branches:
      - "development"
  pull_request:
    branches:
      - "qa"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
  dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'
    needs: build
    environment: 
      name: Development
    env:
      TEST: ${{secrets.TEST}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: |
          echo "I am running $TEST"
  qa:
    runs-on: ubuntu-latest
    needs: build
    if: ${{github.ref == 'refs/heads/qa'}}
    environment: 
      name: qa
    env:
      TEST: ${{secrets.TEST}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: |
          echo "I am running $TEST"