name: Multi-branch Pipeline

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - qa
      - non-prod
    types:
      - "closed"
jobs:
  Build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Output Run ID
        run: echo ${{ github.run_id }}

      - name: Output Run ID
        run: |
          env.BUILD_NUMBER = sh(
            script: 'node -pe "require(\'./package.json\').version"',
            returnStdout: true
          ).trim()
          echo env.BUILD_NUMBER

      - name: Deploy to environment
        run: |
          if [ "$MYSECRET" == "qa" ]
          then
            echo "Got secret"
          else
            echo "no secret"
          fi
          
          if [ "$env_vars" == "qa" ]
          then
            echo "variables matched"
          else
            echo "variables not matched"
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN}}
