name: Multi-branch Pipeline

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - qa
      - non-prod
    types:
      - "closed"
jobs:
  TEST1:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Output Run ID
        run: echo ${{ github.run_id }}

      - name: Deploy to environment
        run: |
          if [ "$MYSECRET" == "development" ]
          then
            echo "Got secret"
          else
            echo "no secret"
          fi
          
          if [ "$env_vars" == "development" ]
          then
            echo "variables matched"
          else
            echo "variables not matched"
          fi
        env:
          MYSECRET: ${{ secrets.TEST}}
          env_vars: ${{ vars.ETEST }}
  TEST2:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Output Run ID
        run: echo ${{ github.run_id }}

      - name: Deploy to environment
        run: |
          if [ "$MYSECRET" == "qa" ]
          then
            echo "Got secret"
          else
            echo "no secret"
          fi
          
          if [ "$env_vars" == "qa" ]
          then
            echo "variables matched"
          else
            echo "variables not matched"
          fi
        env:
          MYSECRET: ${{ secrets.TEST}}
          env_vars: ${{ vars.ETEST }}