name: Multi-branch Pipeline

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - qa
      - non-prod
    types:
      - "closed"
jobs:
  Setup_AWS:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup AWS
        run: |
          BUILD_NUMBER=$(awk '/version/{gsub(/("|",)/,"",$2);print $2};' package.json)
          echo $BUILD_NUMBER
          mkdir ~/.aws && echo "[default]\nregion=us-west-2\noutput=json" > ~/.aws/config
          cat ~/.aws/config
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN}}

      - name: Setup environment
        run: |
          if [ ${{ github.ref_name }} == "development" ]
          then
            echo "\nNODE_ENV=${{ github.ref_name}}" >> .env
            cat .env
          elif [ ${{ github.ref_name }} == "qa" ]
          then
            echo "\nNODE_ENV=stage" >> .env
            cat .env
          elif [ ${{ github.ref_name }} == "non-prod" ]
          then
            echo "\nNODE_ENV=production" >> .env
            cat .env
          else
            echo "${{ github.ref_name }} not found"
          fi
      - name: testing
        run: |
          cat .env
          
