name: non-prod build

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/non-prod'
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      # uses: actions/setup-node@v3
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    # - run: npm ci
    - name: build
      run: npm run build
    - run: npm test
    
    # Share artifact inside workflow
    - name: Share artifact inside workflow
      uses: actions/upload-artifact@v3
      with:
        name: react-github-actions-build
        path: build