name: Build React App

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - qa
      - non-prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build