name: React Build

on:
  pull_request:
    branches:
      - development
      - qa
      - non-prod

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build for development
        if: ${{ github.ref == 'refs/heads/development' }}
        env:
          APP_ENV: "development"
        run: npm run build

      - name: Build for QA
        if: ${{ github.ref == 'refs/heads/qa' }}
        env:
          APP_ENV: "qa"
        run: npm run build
