# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["qa","non-prod","main"]
  workflow_dispatch:
  
jobs:
  Build_dev:
    name: Build Development
    if: github.ref == 'refs/heads/origin/development' 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    environment: 
      name: Development
    steps:
      - name: dev build
        uses: actions/checkout@v2
      - run: ls
      - run: echo $TEST
  Build_qa:
    name: Build qa
    if: github.ref == 'refs/heads/origin/qa' 
    # if: github.ref == 'refs/heads/origin/qa'
    # if: github.event_name == 'pull_request' || github.ref == 'refs/heads/origin/qa'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    environment: 
      name: qa
    steps:
      - name: dev build
        uses: actions/checkout@v2
      - run: ls
  Build_nonprod:
    name: Build non-prod
    if: github.ref == 'refs/heads/origin/non-prod'
    # if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    environment: 
      name: non-prod
    steps:
      - name: dev build
        uses: actions/checkout@v2
      - run: ls 
  Build_main:
    name: Build main
    if: github.ref == 'refs/heads/origin/main'
    # if: github.event_name == 'pull_request' || github.ref == 'refs/heads/origin/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    environment: 
      name: qa
    steps:
      - name: dev build
        uses: actions/checkout@v2
      - run: ls 