name: Build and Deploy

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - qa
      - non-prod
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: ${{ github.event_name == 'pull_request' && github.base_ref == 'qa' && 'qa' || github.base_ref == 'non-prod' && 'non-prod' || github.base_ref == 'main' && 'main' || 'development' }}
      BUILD_TAG: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo "env.TEST1"
